### ISSUE TITLE
Whoops I still have access to this :) 

### ISSUE THREAD

**Issue by jordancardwell** [icanbwell/SparkPipelineFramework#325]
I just noticed I still have access to this, someone likely just needs to remove my individual github account from the repo.

**Comment by jordancardwell** [comment]
actually i see other FHIR things if I go to icanbwell's org page.. I might still be a member of some helix/fhir group

**Comment by jordancardwell** [comment]
@imranq2 ☝️ just a heads-up

**Comment by imranq2** [comment]
These are open source projects :-)
